[package]
name = "prk_mdgen"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.7"
rayon = "1.6"
lazy_static = "1.4"
clap = { version = "4.1", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.19.1"
indoc = "2"
